### PR TITLE
tests: Remove dependency on  sys/time.h

### PR DESCRIPTION
**Pull request by tmmsartor**
`sys/time.h` is not present in MSVC by default
as mentioned in [giaf/blasfeo #48](https://github.com/giaf/blasfeo/pull/48)

### CODE REVIEW

**Comment by giaf** [comment]
To what I got, time() and gettimeofday() are not equivalent, since time() has second resolution, while gettimeofday() has micro-second resolution.

I guess the solution is to define a blasfeo_tic() and blasfeo_toc() similarly to what done in acados here
https://github.com/acados/acados/blob/master/acados/utils/timing.c

**Comment by roversch** [comment]
@giaf Do you want @tmmsartor to fix this or should I merge ?

**Comment by tmmsartor** [comment]
@giaf 
My point was that for the tests you don't need that time accuracy. At now, time measurements have the only purpose to give a rough idea about how long does it take to run the specific subset of tests, usually greater than 1 second.
In benchmarks is stil used `gettimeofday` with microseconds accuracy, I will test the alternatives on windows before pushing the changes.

**Comment by giaf** [comment]
ok good

**Pull request merged**
